### ISSUE TITLE
API jar not available in Maven Repository at http://gitblit.github.io/gitblit-maven/ or central

### ISSUE THREAD

**Issue by gitblit** [gitblit/gitblit#589]
Originally reported on Google Code with ID 293

```
What steps will reproduce the problem?
1. Search for gbapi in central/gitblit-maven repository
2. No jar package is listed. 


What is the expected output? What do you see instead?
I would have wished a gb-api jar file available for consumption through Maven dependency
mechanism. However, no API jar is available. 

What version of the product are you using? On what operating system?
1.3.1

Please provide any additional information below.

API jar availability is critical for gitblit to succeed in the integrated  applications.



```

Reported by `meetdestiny` on 2013-08-09 04:29:21

**Comment by darmbrust** [comment]
This is rather unfortunate that you won't push to maven central.  Is there a reason?  

Or is it purely a time / resources issue?  

I have a desire to use the RPC library code to remotely hit  gitblit service, but I can't integrate it into my code base properly because it won't build for anyone, when it can't find the dependencies without messing with the maven configurations.

Which will likely lead to us doing copy/paste code inheritance... which is terrible.

I've pushed other things to maven central, and could offer some help.

**Comment by gitblit** [comment]
Hi @darmbrust.  You can add the github-hosted Maven repo and api jar file to your pom today.  True, the jar is still not hosted on Maven Central.  Maybe some day it will be but it's not a high priority for me.

**Comment by darmbrust** [comment]
Hmm, not sure if that mechanism works for our environment or not - we directly all maven requests through our nexus repository.  Thanks for the idea though.
