### ISSUE TITLE
adding invalid SSH key to user profile causes profile rendering to break

### ISSUE THREAD

**Issue by nezroy** [gitblit/gitblit#924]
If you add an invalid SSH key to a user profile, it can cause the profile rendering for that user to break completely until the invalid key is manually removed from that user's keystore.

On a 1.6.2 self-hosted/GO install, I was copy/pasting a valid SSH key to the SSH keys in my user profile, but ended up with some linebreaks in the middle of the key. From that point that specific user's profile page would constantly fail to render, with the following error in the server console output. I had to manually remove the broken multi-line key from the user's keystore file to fix.

2015-09-27 23:35:01 [INFO ] loading ssh keystore for nezroy
2015-09-27 23:35:01 [ERROR] Error attaching this container for rendering: [MarkupContainer [Component id = sshKeysPanel]]
org.apache.wicket.WicketRuntimeException: Error attaching this container for rendering: [MarkupContainer [Component id = sshKeysPanel]]
        at org.apache.wicket.MarkupContainer.onBeforeRenderChildren(MarkupContainer.java:1789)
        at org.apache.wicket.Component.onBeforeRender(Component.java:4001)
        at org.apache.wicket.Component.internalBeforeRender(Component.java:1069)
        at org.apache.wicket.Component.beforeRender(Component.java:1103)
        at org.apache.wicket.MarkupContainer.onBeforeRenderChildren(MarkupContainer.java:1777)
        at org.apache.wicket.Component.onBeforeRender(Component.java:4001)
        at org.apache.wicket.Component.internalBeforeRender(Component.java:1069)
        at org.apache.wicket.Component.beforeRender(Component.java:1103)
        at org.apache.wicket.MarkupContainer.onBeforeRenderChildren(MarkupContainer.java:1777)
        at org.apache.wicket.Component.onBeforeRender(Component.java:4001)
        at org.apache.wicket.Page.onBeforeRender(Page.java:1555)
        at com.gitblit.wicket.pages.BasePage.onBeforeRender(BasePage.java:152)
        at org.apache.wicket.Component.internalBeforeRender(Component.java:1069)
        at org.apache.wicket.Component.beforeRender(Component.java:1103)
        at org.apache.wicket.Component.prepareForRender(Component.java:2297)
        at org.apache.wicket.Page.prepareForRender(Page.java:1545)
        at org.apache.wicket.Component.prepareForRender(Component.java:2329)
        at org.apache.wicket.Page.renderPage(Page.java:912)
        at org.apache.wicket.request.target.component.BookmarkablePageRequestTarget.respond(BookmarkablePageRequestTarget.java:261)
        at org.apache.wicket.request.AbstractRequestCycleProcessor.respond(AbstractRequestCycleProcessor.java:105)
        at org.apache.wicket.RequestCycle.processEventsAndRespond(RequestCycle.java:1287)
        at org.apache.wicket.RequestCycle.step(RequestCycle.java:1358)
        at org.apache.wicket.RequestCycle.steps(RequestCycle.java:1465)
        at org.apache.wicket.RequestCycle.request(RequestCycle.java:545)
        at org.apache.wicket.protocol.http.WicketFilter.doGet(WicketFilter.java:486)
        at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:319)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
        at com.gitblit.servlet.EnforceAuthenticationFilter.doFilter(EnforceAuthenticationFilter.java:87)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
        at com.gitblit.servlet.ProxyFilter$1.doFilter(ProxyFilter.java:74)
        at com.gitblit.servlet.ProxyFilter.doFilter(ProxyFilter.java:77)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:497)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:610)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:539)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.sshd.common.util.Buffer$BufferException: Underflow
        at org.apache.sshd.common.util.Buffer.ensureAvailable(Buffer.java:365)
        at org.apache.sshd.common.util.Buffer.getRawBytes(Buffer.java:234)
        at org.apache.sshd.common.util.Buffer.getRawBytes(Buffer.java:230)
        at org.apache.sshd.common.util.Buffer.getBytes(Buffer.java:225)
        at org.apache.sshd.common.util.Buffer.getMPIntAsBytes(Buffer.java:216)
        at org.apache.sshd.common.util.Buffer.getMPInt(Buffer.java:212)
        at org.apache.sshd.common.util.Buffer.getRawPublicKey(Buffer.java:256)
        at com.gitblit.transport.ssh.SshKey.getPublicKey(SshKey.java:73)
        at com.gitblit.transport.ssh.SshKey.getAlgorithm(SshKey.java:82)
        at com.gitblit.wicket.panels.SshKeysPanel$1.populateItem(SshKeysPanel.java:75)
        at org.apache.wicket.markup.repeater.RefreshingView$1.newItem(RefreshingView.java:114)
        at org.apache.wicket.markup.repeater.DefaultItemReuseStrategy$1.next(DefaultItemReuseStrategy.java:71)
        at org.apache.wicket.markup.repeater.DefaultItemReuseStrategy$1.next(DefaultItemReuseStrategy.java:68)
        at org.apache.wicket.markup.repeater.RefreshingView.addItems(RefreshingView.java:189)
        at org.apache.wicket.markup.repeater.RefreshingView.onPopulate(RefreshingView.java:98)
        at org.apache.wicket.markup.repeater.AbstractRepeater.onBeforeRender(AbstractRepeater.java:131)
        at org.apache.wicket.markup.repeater.AbstractPageableView.onBeforeRender(AbstractPageableView.java:121)
        at org.apache.wicket.Component.internalBeforeRender(Component.java:1069)
        at org.apache.wicket.Component.beforeRender(Component.java:1103)
        at org.apache.wicket.MarkupContainer.onBeforeRenderChildren(MarkupContainer.java:1777)
        ... 48 more

**Comment by gitblit** [comment]
This should be fixed on both `master` and `develop`.

**Comment by gitblit** [comment]
Already fixed, AFAICT.

**Comment by drthornt** [comment]
I'm running 1.6.2 and i have this problem. Where is it fixed?

**Comment by drthornt** [comment]
Hilariously if I remove the user and re-add it ... the problem persist. This is a security concern. New users should not inherit data from old users.

**Comment by gitblit** [comment]
Ah.  Yes, the key manager does not know about user deletion.  Agreed, this should be fixed.  Care to make a PR?
